### ISSUE TITLE
Stolen from AssetoCorsa?

### ISSUE THREAD

**Issue by TunderTunder** [PERRINN/project-424-unity#81]

**Comment by EdyJ** [comment]
If you are referring to the Nürburgring-Nordschleife map, it was licensed to us by Ohw Studios, the owners and map providers for Kuno Simulazioni, the creators of Assetto Corsa. This license grants us permission to include the map in our open-source project.

**Comment by EdyJ** [comment]
https://github.com/PERRINN/project-424-unity/blob/master/Assets/Locations/Nordschleife/LICENSING.txt
