### ISSUE TITLE
repository access to public its private

### ISSUE THREAD

**Issue by frankmwito** [PERRINN/project-424-unity#87]
hey the repository would not clone because am having access rights of your repository would you please kindly help me with the permissions for the access to clone the repository because its private

**Comment by EdyJ** [comment]
Hello, the repository is public to anyone. We haven't configured any special permissions. Ensure you're trying to clone the correct URL.

![image](https://github.com/PERRINN/project-424-unity/assets/6773528/d0274095-fd04-436c-b7e2-5fcbb95bcec1)

**Comment by frankmwito** [comment]
Okay thanks for the reply let me try the other option I've been trying to
see if I can make your project to meet there gaming needs for the deaf and
blind children using text into speech and Ai as the autopilot but also a
directional giver for the players

**Comment by EdyJ** [comment]
Thank you for your interest. The project is public and everyone is welcome to fork it and use it.
